import type { BotIdentity, Organization, Person, Universe } from './types';
export const BOT_DISCLAIMER =
  'This edit was generated by a NotingBot using source material. It is not a statement by any person, organization, coalition, or campaign unless reviewed and approved by an authorized human.';
export const fairRentUniverse: Universe = {
  id: 'fairrentnyc',
  slug: 'fairrentnyc',
  name: 'Fair Rent NYC / Commercial Rent Stabilization Movement Memory',
  subdomain: 'fairrentnyc.noting.us',
  visibility: 'team_internal',
  description: 'Private movement-memory prototype for Commercial Rent Stabilization collaboration.',
  sourceStatusDate: '2026-05-29',
};
export const organizations: Organization[] = [
  'Fair Rent NYC',
  'NYC Artist Coalition',
  'Action Lab',
  'Small Business United',
  'TakeRoot Justice',
  'Chhaya CDC',
  'Cooper Square Committee',
  'Street Vendor Project',
].map((name, i) => ({ id: `org-${i + 1}`, name }));
export const people: Person[] = ['Jamie Burkart', 'Irene Tung', 'Olympia Kazi', 'Noting Admin'].map(
  (displayName, i) => ({ id: `person-${i + 1}`, displayName }),
);
export const bots: BotIdentity[] = [
  'Meeting-Synthesis',
  'Source-Grounding',
  'Decision-Extractor',
  'Privacy-Check',
  'Legal-Claim-Check',
  'Movement-Memory-Gardener',
].map((n) => ({
  id: `notingbot-${n.toLowerCase()}`,
  name: `NotingBot/${n}`,
  purpose: `Deterministic demo assistance for ${n}.`,
  disclaimer: BOT_DISCLAIMER,
}));
