import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { Nav } from '../../../../../components/Nav';
import { bundles } from '../../../../../lib/demo';

function readReviewEvents(slug: string) {
  const path = 'content/demo/fairrentnyc/review-events.jsonl';
  if (!existsSync(path)) return [];
  return readFileSync(path, 'utf8')
    .trim()
    .split('\n')
    .filter(Boolean)
    .map((line) => JSON.parse(line))
    .filter((event) => event.bundleSlug === slug);
}

function readRevisions(slug: string) {
  const dir = `content/demo/fairrentnyc/bundles/${slug}/revisions`;
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .sort()
    .map((file) => ({ file, body: readFileSync(`${dir}/${file}`, 'utf8') }));
}

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const b = bundles.find((x) => x.slug === slug) ?? bundles[0];
  const reviewEvents = readReviewEvents(b.slug);
  const revisions = readRevisions(b.slug);
  return (
    <>
      <Nav />
      <h1>{b.wikiTitle}</h1>
      <p>
        <span className="badge">{b.pageType}</span>
        <span className="badge">{b.metadata.status}</span>
        <span className="badge">review {b.metadata.reviewStatus}</span>
        <span className="badge">{b.metadata.visibility}</span>
        <span className="badge">consent {b.metadata.consentLevel}</span>
      </p>
      <div className="card warn">
        <b>Generated by:</b> {b.metadata.generatedBy}
        <br />
        <b>Source status date:</b> {b.metadata.sourceStatusDate}
        <br />
        <b>Public use:</b> {String(b.metadata.publicUseAllowed)} | <b>Legal advice:</b>{' '}
        {String(b.metadata.legalAdvice)}
        <br />
        <b>Export status:</b>{' '}
        {b.permissions.exportAllowed ? 'eligible with sidecars' : 'blocked by permissions'}
      </div>
      <h2>Rendered Markdown</h2>
      <article className="card">
        {b.markdown.split('\n').map((line, index) => (
          <p key={index}>{line}</p>
        ))}
      </article>
      <h2>Raw page.md</h2>
      <pre>{b.markdown}</pre>
      <h2>Metadata</h2>
      <pre>{JSON.stringify(b.metadata, null, 2)}</pre>
      <h2>Sources / Citations</h2>
      {b.sources.map((s) => (
        <div className="card" key={s.id}>
          <b>{s.label}</b>
          <p>
            {s.artifactId}: {s.segmentIds.join(', ')}
          </p>
          {s.quote ? <blockquote>{s.quote}</blockquote> : null}
        </div>
      ))}
      <h2>Evals</h2>
      {b.evals.map((e) => (
        <div className={`card ${e.status}`} key={e.id}>
          <b>
            {e.name}: {e.status}
          </b>
          <p>{e.notes}</p>
        </div>
      ))}
      <h2>Permissions</h2>
      <pre>{JSON.stringify(b.permissions, null, 2)}</pre>
      <h2>Wiki Export</h2>
      <pre>{b.wikiPreview}</pre>
      <h2>Revisions</h2>
      {revisions.map((revision) => (
        <details className="card" key={revision.file}>
          <summary>{revision.file}</summary>
          <pre>{revision.body}</pre>
        </details>
      ))}
      <h2>Review History</h2>
      {reviewEvents.length ? (
        reviewEvents.map((event) => (
          <div className="card" key={event.id}>
            <b>{event.action}</b> by {event.actorId} at {event.createdAt}
            <p>{event.note}</p>
            <p>
              <b>Result:</b> {event.resultingReviewStatus}
            </p>
          </div>
        ))
      ) : (
        <p>No review events recorded for this bundle.</p>
      )}
    </>
  );
}
