import { mkdir, writeFile, rm } from 'node:fs/promises';
import { sourceArtifacts, runningMinutesExcerpt, generateFairRentPageBundles } from '@noting/fixtures';
const root='content/demo/fairrentnyc';
const artifacts=sourceArtifacts(); const bundles=generateFairRentPageBundles(artifacts);
await mkdir(`${root}/sources`,{recursive:true}); await mkdir(`${root}/bundles`,{recursive:true}); await rm(`${root}/bundles`,{recursive:true,force:true}); await mkdir(`${root}/bundles`,{recursive:true});
await writeFile(`${root}/sources/running-minutes-2026-05-29.excerpt.md`,runningMinutesExcerpt);
await writeFile(`${root}/sources/running-minutes-2026-05-29.segments.jsonl`,artifacts[0].segments.map(s=>JSON.stringify(s)).join('\n')+'\n');
await writeFile(`${root}/sources/movement-map-policy-lineages.fixture.json`,JSON.stringify(artifacts[1],null,2));
await writeFile(`${root}/sources/legislative-provenance-redline.fixture.md`,`# ${artifacts[2].title}\n\n${artifacts[2].notes}\n\n- [source:${artifacts[2].id}#seg-how-to-read]\n`);
await writeFile(`${root}/sources/archival-email-consent-boundary.fixture.md`,`# ${artifacts[3].title}\n\n${artifacts[3].notes}\n\nCurrent consent must be confirmed before public use.\n`);
await writeFile(`${root}/sources/source-catalog.fixture.json`,JSON.stringify(artifacts.map(a=>({id:a.id,title:a.title,sourceType:a.sourceType,visibility:a.visibility,publicUseAllowed:a.publicUseAllowed})),null,2));
for(const b of bundles){const dir=`${root}/bundles/${b.slug}`; await mkdir(`${dir}/revisions`,{recursive:true}); await writeFile(`${dir}/page.md`,b.markdown); await writeFile(`${dir}/page.meta.json`,JSON.stringify({...b.metadata,noting_id:b.metadata.notingId,page_type:b.pageType,wiki_title:b.wikiTitle,review_status:b.metadata.reviewStatus,source_artifacts:b.metadata.sourceArtifacts,source_status_date:b.metadata.sourceStatusDate,public_use_allowed:b.metadata.publicUseAllowed,legal_advice:b.metadata.legalAdvice,generated_by:b.metadata.generatedBy},null,2)); await writeFile(`${dir}/sources.jsonl`,b.sources.map(s=>JSON.stringify(s)).join('\n')+'\n'); await writeFile(`${dir}/evals.json`,JSON.stringify(b.evals,null,2)); await writeFile(`${dir}/permissions.json`,JSON.stringify(b.permissions,null,2)); await writeFile(`${dir}/wiki-export.wikitext`,b.wikiPreview); await writeFile(`${dir}/revisions/2026-06-23T090000Z.bot-draft.md`,b.markdown); if(b.slug==='legal-bill-text-review'){await writeFile(`${dir}/revisions/2026-06-23T101500Z.human-correction.md`,b.markdown.replace('Several provisions need legal / policy review before becoming settled campaign position.','Several provisions are flagged as needing legal / policy review as of the 2026-05-29 source date; they are not settled campaign position in this demo.'))}}
await mkdir(`${root}/export-preview`,{recursive:true}); await writeFile(`${root}/export-preview/README.md`,'Export preview preserves page.md, page.meta.json, sources.jsonl, evals.json, permissions.json, and wiki-export.wikitext.\n');
console.log(`Seeded ${artifacts.length} source artifacts and ${bundles.length} page bundles.`);
