import { expect, it } from 'vitest';
import { sourceArtifacts, generateFairRentPageBundles } from './index';
it('generates at least eight attributed bundles', () => {
  const b = generateFairRentPageBundles(sourceArtifacts());
  expect(b.length).toBeGreaterThanOrEqual(8);
  expect(b.every((x) => x.markdown.includes('This edit was generated by a NotingBot'))).toBe(true);
  expect(b.every((x) => x.sources.length > 0)).toBe(true);
});
